export const infoObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDescription: true,
  topLine: "We dance...",
  headline: "Breaking is in our heart...",
  description: "...so we have to practice as much as we can.",
  buttonLabel: "Contact us",
  imgStart: false,
  img: "../../images/NS-logo (1).svg",
  alt: "Ns Logo large",
  dark: true,
  primary: true,
  darkText: false,
};

export const infoObjTwo = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDescription: false,
  topLine: "We teach...",
  headline: "We pass our knowledge to younger generations...",
  description: "...and hope they get the passion for breaking that we have.",
  buttonLabel: "Contact us",
  imgStart: true,
  img: "../../images/NS-logo (1).svg",
  alt: "Ns Logo large",
  dark: false,
  primary: false,
  darkText: true,
};
